################################################################################
#      NOTE: IF YOU CHANGE ANYTHING IN THIS FILE, YOU MUST RESTART YOUR        #
#            LOCAL JEKYLL SERVER FOR THE CHANGES TO BE APPLIED                 #
################################################################################

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Grammar Effects
tagline:          'for accurate reading, skillful writing, and reliable paraphrasing.'
description:      'Grammar Effects is a website for learning and practicing accurate reading, skillful writing, and reliable paraphrasing.'
url:              https://srogersact.github.io/
baseurl:          /

author:
  name:           'Stephen Rogers'
  # url:            https://srogersact.github.io/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/srogersact/srogersact.github.io
